### ISSUE TITLE
Check database integrity

### ISSUE THREAD

**Issue by yotaae** [openkfw/mapme.protectedareas#84] opened 2022-03-03 11:05 UTC
Hi @Jo-Schie @melvinhlwong,

- [x] summary statistcs for current database (raw data) and/or maps to check plausibility (ideally: create reproducible scripts for the analysis of matched data later)

we have two problems related to treatment assignment in the matching frames:

- [x] Check treatment assignment outside of treated PAs: 1,352 polygons are falsely marked as treated in every matching frame. @Jo-Schie, we have already talked about this.
- [x] Check cells inside of treated PAs: Some treated PAs do not have any cells (neither treatment nor control) inside. We should check why this is the case.
- [x] Our out-dataframes and matched panels for year 2005 contain duplicates in terms of poly-id (after filtering for year_standard == 0). See second screenshot below.
- [x] Check if country and clay_content_10_cm contain NAs (and other variables, just to be sure)

For illustration of the first two issues, I have attached a map of the cells included in matching frame 2006: 
(1) Blue cells (treatment) outside of PAs that were supported in 2006 (yellow Polygons). 
(2) No blue cells in some of the supported PAs. All yellow polygons (at least the larger ones) should include at least some treatment cells, correct?

![Matching_frame_2006_map](https://user-images.githubusercontent.com/84446823/156550377-fc74b738-56d3-4704-a3a5-aa9f2e86cf1c.PNG)

Third problem:

![year2005_issues](https://user-images.githubusercontent.com/84446823/156552008-17f58297-e37a-4802-a5b0-1e7d3cde53f0.PNG)

**Comment by melvinhlwong** [comment] 2022-03-28 12:47
@Jo-Schie 

- [ ] Describe how treatment variable is created in matching frame (write down here)

**Comment by yotaae** [comment] 2022-03-28 13:57
Problems related to treatment assignment and missing cells in treated PAs seems to be solved, at least in the year 2006 - see screenshot below. 
![image](https://user-images.githubusercontent.com/84446823/160414020-3036c8e3-743b-4e8d-9ede-5a80e3c5e4ea.png)

**Comment by yotaae** [comment] 2022-03-28 16:03
@Jo-Schie @melvinhlwong 

I've just checked the treatment cells in some other years - looks fine in most years. 

One exception is the year 2012 (see screenshot below): Some treated PAs do not have treatment cells in them. Is this related to the conservation category being "UNESCO-MAB Biosphere Reserve"? All of the respective PAs belong to this category. I remember an issue by @Jo-Schie saying something about this conservation category but can't find the issue. 

![image](https://user-images.githubusercontent.com/84446823/160439840-041678b1-5572-4604-a4f9-61ba3a5a5a5f.png)

**Comment by yotaae** [comment] 2022-04-04 16:12
NA problem to remember/ check after adaption of treatment assignment in matching frames: NA values for covariates in matching frames. Related to filtering PAs (e.g. marine areas without tree cover etc.) -> Filtering may solve this problem. See screenshot of NA values below: 

![image](https://user-images.githubusercontent.com/84446823/161586609-66890927-6620-4af9-b043-8a5500bf0288.png)

**Comment by Jo-Schie** [comment] 2022-04-09 13:29
> @Jo-Schie
> 
> * [x]  Describe how treatment variable is created in matching frame (write down here)
> * [x]  Describe how matching frames ensure that treatment cell in one year can not be control cell in another year

@melvinhlwong and @yotaae : 

- Treatment variable is created by identification of start year from project documentation. Via WDPA ID this information is then assigned to the gridcells. Treated cells are intersecting treated WDPA polygon areas (they cross the boarder -> conservative estimate that includes potential leakage in boarder regions). 
- Treatment cells cannot be controls cells because all polygon cells that intersect any WDPA area are excluded as controls (see also the maps in the referenced issues below). 

Please see issue #88 for maps with results.

**Comment by Jo-Schie** [comment] 2022-04-12 13:46
it would be great to have a map or more information why we face this missing values.

**Comment by Jo-Schie** [comment] 2022-04-14 16:29
Treecover is definitely processing related. Darius en outed similar issues. @goergen95  could you please have a quick look or comment? Maybe you can provide us a quick fix...

**Comment by yotaae** [comment] 2022-04-18 17:05
@Jo-Schie, you can see missings for for treecover in the treatment group, e.g. the spike in 2009. Just a little difficult to see because the pattern for missings are the same for treecover, loss, loss_t3 and emissions -> colors of the lines are are mixed. Does that answer the question?

**Comment by Jo-Schie** [comment] 2022-05-14 13:01
I can confirm that the missing values issue in the forest cover dataset is related to the input data.

**Comment by yotaae** [comment] 2022-06-02 09:34
Update on missing data for treecover: We have much less missing values now: ~150k before, 5k now. See screenshot with remaining cells with missing data for treecover below:

![image](https://user-images.githubusercontent.com/84446823/171601199-6bfd1966-65f8-48d3-bddb-3437fb7410d4.png)

**Comment by Jo-Schie** [comment] 2022-06-07 12:13
solved via email.

**Closed by Jo-Schie** 2022-06-07 12:13 UTC
Labels: 1_Must, Database
